import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const header = (
  <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image
          src="/logo.png"
          width={40}
          height={40}
          className="mx-auto"
          alt={"logo"}
        />
      <Link href="/">
          <h1 className="text-2xl text-white font-bold mt-4">Jack's Blog</h1>
      </Link>
      <p className='text-slate-300'>Welcome to my tech blog.</p>
    </div>
  </header>
)

const footer = (
  <footer>
      <div className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
        <h3>Designed by Pixegami</h3>
    </div>
  </footer>
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-black mx-auto p-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}
